### ISSUE TITLE
Long 'words' to not wrap and extend beyond the space allocated to the post

### ISSUE THREAD

**Issue by TwelfthGhast** [OleVik/grav-theme-project-space#10]
Title.

Fresh install of grav through docker image, installed theme through GUI and created three test posts.

![image](https://user-images.githubusercontent.com/8342539/83397955-cdc09000-a441-11ea-98ec-1bf9f3b16383.png)

**Comment by OleVik** [comment]
This should be solved by [v1.2.6](https://github.com/OleVik/grav-theme-project-space/releases/tag/v1.2.6).
