### ISSUE TITLE
[Question] Page layout error

### ISSUE THREAD

**Issue by ecardm** [OleVik/grav-theme-project-space#12]
Sorry if this is noob question, but do I have to install the skeleton version of Project Space? I tried to install the theme after setting up Grav but it seems the layout is not working properly.
![Screenshot_2020-08-22 Project Space](https://user-images.githubusercontent.com/70065369/90958468-52fa9480-e4c7-11ea-8e46-b1be81dbdef0.png)

**Comment by OleVik** [comment]
It appears that [languages.yaml](https://github.com/OleVik/grav-theme-project-space/blob/master/languages.yaml) is missing from your installation. How did you install Grav and the theme, and did you try reinstalling the theme?
