### ISSUE TITLE
Unpublished pages show in menu

### ISSUE THREAD

**Issue by anendel** [OleVik/grav-theme-project-space#3]
Since this is my first Grav project ever and I have no coding background at all, I don't seem to be able to solve this myself:

I have a few pages which are not published and should be hidden, still they do show up in the menu on the right side.  Can this be updated so only published pages are shown?

**Comment by OleVik** [comment]
Sure, [quick fix](https://github.com/OleVik/grav-theme-project-space/commit/32259fc84bf42ca39f7847318df93b6ff885751d) will be in v1.2.1.
