### ISSUE TITLE
Categories are replaced with ID after saving

### ISSUE THREAD

**Issue by anendel** [OleVik/grav-theme-project-space#4]
Maintaining Grav v1.5.8 using Admin v1.8.17 it seems that once a page is saved, the category on the front-end is replaced with an ID instead of the actual label.

The categories were listed in both project-space.yaml (theme) and site.yaml (user/config).

**Comment by OleVik** [comment]
I have [a fix](https://github.com/OleVik/grav-theme-project-space/commit/2fdb532e9cb234b343e683e5251d8760a9ba480f) for [v1.2.1](https://github.com/OleVik/grav-theme-project-space/releases/tag/v1.2.1) - should be in the GPM soon.
