### ISSUE TITLE
GPM Package Tragically B0rked

### ISSUE THREAD

**Issue by leycec** [OleVik/grav-theme-project-space#8]
*Oh, noes!* Recent updates to `quark` appear to have broken the `project-space` package:

```
$ bin/gpm install project-space

GPM Releases Configuration: Stable



Dependency quark is required in an older version than the latest release available, and it cannot be installed. This package must be updated. Please get in touch with its developer.
```

**It is tragic.** Thankfully, the ZIP-based manual approach is still our friend. :weary:

**Comment by OleVik** [comment]
I think the travesty will be resolved in [v1.2.3](https://github.com/OleVik/grav-theme-project-space/releases/tag/v1.2.3), wherein version constraints are raised to be more lenient.
